site_name: Dual Narration - Project Documentation
site_description: Research project documentation and working notes
site_url: https://yourusername.github.io/dual-narration  # Update with your GitHub username

# Repository
repo_name: yourusername/dual-narration  # Update with your GitHub repo
repo_url: https://github.com/yourusername/dual-narration  # Update with your GitHub repo

# Theme configuration
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: JetBrains Mono
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
      tags_file: tags.md
  - blog:
      blog_dir: posts
      blog_toc: true
      post_date_format: medium
      post_url_format: "{date}/{slug}"
      categories_allowed:
        - Research
        - Analysis
        - Notes
        - Experiment
        - Theory
        - Implementation
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Navigation
nav:
  - Home: index.md
  - About: about.md
  - Posts: posts/index.md
  - Tags: tags.md

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/dual-narration  # Update with your repo
  tags:
    Research: red
    Analysis: blue
    Notes: green
    Experiment: orange
    Theory: purple
    Implementation: teal